### ISSUE TITLE
No es necesario

### ISSUE THREAD

**Issue by RicardoMaldonado93** [nico1311/angular-blog#1]
El Type Require aca no es necesario, se podria utiilizar en caso de que fuese un @Input, y que para este sea opcional la escritura.

https://github.com/nico1311/angular-blog/blob/d050d6d439f2b14ed65bf923819e20c887735085/src/app/modules/albums/album-details/album-details.component.ts#L20

https://github.com/nico1311/angular-blog/blob/d050d6d439f2b14ed65bf923819e20c887735085/src/app/modules/albums/album-gallery/album-gallery.component.ts#L20

https://github.com/nico1311/angular-blog/blob/d050d6d439f2b14ed65bf923819e20c887735085/src/app/modules/posts/post-details/post-details.component.ts#L20

https://github.com/nico1311/angular-blog/blob/d050d6d439f2b14ed65bf923819e20c887735085/src/app/modules/users/user-details/user-details.component.ts#L22

**Comment by nico1311** [comment]
Lo tengo en cuenta, gracias!
