### ISSUE TITLE
Orden de los componentes

### ISSUE THREAD

**Issue by RicardoMaldonado93** [nico1311/angular-blog#2]
En general esta bien el orden de las carpetas, pero deberias fraccionarlo de la siguiente manera para una buena escabilidad y mantenimiento 

```
src
--app
	--pages
		--albums
		--posts
		--todos
		--user
	--services
		--albumService
		--postsService
		--todosService
		--userService
	--components
		--componentA
		--componentB
		--componentC
	--models
	        --IUser
	        --IPost
	--utils
		--pipes
		--constants
	--vendor
		--material
	--assets
		--styles
		--fonts
		--images
```

**Comment by nico1311** [comment]
Gracias por el feedback! Estoy al tanto, en general esa es la estructura que trato de usar en React/Next. En este caso, lo que se nos había pedido es que la app esté separada en módulos y sea lo más fácil posible quitar un módulo, por eso usé esta estructura, de modo que lo único que haría falta para eliminar un módulo es borrar el subdirectorio de `modules` y quitarlo del `app-routing`.
